language: cpp
env:
  - compiler='g++-4.8' build_type='Debug'
  - compiler='g++-4.8' build_type='Release'
  - compiler='g++-4.9' build_type='Debug'
  - compiler='g++-4.9' build_type='Release'
  - compiler='g++-5' build_type='Debug'
  - compiler='g++-5' build_type='Release'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - libboost1.55-all-dev
    - g++-4.8
    - g++-4.9
    - g++-5
install:
  - cd ../
  - wget --no-check-certificate https://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz
  - tar -xzf cmake-3.3.1-Linux-x86_64.tar.gz
  - wget --no-check-certificate http://llvm.org/releases/3.8.0/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
  - tar -xJf clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
  - mv clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04 llvm-3.7
  - export CC='gcc-4.8'
  - export CXX=$compiler
  - $CXX --version
  - cd standardese/
script:
  - mkdir $CXX && cd $CXX
  - ../../cmake-3.3.1-Linux-x86_64/bin/cmake -DCMAKE_BUILD_TYPE=$build_type -DCMAKE_CXX_FLAGS="-Wall -Wextra -pedantic -Wno-parentheses" -DLIBCLANG_LIBRARY=../../llvm-3.7/lib/libclang.so -DLIBCLANG_INCLUDE_DIR=../../llvm-3.7/include/ -DLIBCLANG_SYSTEM_INCLUDE_DIR=../../llvm-3.7/lib/clang/3.7.0/include -DSTANDARDESE_BUILD_TOOL=OFF ../
  - ../../cmake-3.3.1-Linux-x86_64/bin/cmake --build .
  - ./test/standardese_test
